#version: "3"
#
#services:
#
#  selenium-hub:
#    image: selenium/hub:4.18.1
#    container_name: selenium-hub
#    ports:
#      - "4444:4444"   # Expose Grid UI
#    networks:
#      - grid
#
#  chrome:
#    image: selenium/node-chrome:4.18.1
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub   # Connect to hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#    networks:
#      - grid
#
#  firefox:
#    image: selenium/node-firefox:4.18.1
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#    networks:
#      - grid
#
#  edge:
#    image: selenium/node-edge:4.18.1
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#    networks:
#      - grid
#
#networks:
#  grid: