apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox-node
  namespace: automation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: firefox-node
  template:
    metadata:
      labels:
        app: firefox-node
    spec:
      containers:
        - name: firefox-node
          image: selenium/node-firefox:4.18.1
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
